{{ if empty .Values.volume.name }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/"

{{ end }}


{{ if eq .Values.volume.custom "true" }}

{{ .Values.volume.customSetting }}

{{ end }}


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.pvcName | default "pvc" }}
spec:
  accessModes:
    - {{ .Values.volume.accessModes}}
  storageClassName: {{ .Values.volume.storageClassName}} 
  resources:
    requests:
      storage: {{ .Values.volume.storageSize}} 
  volumeName: {{ .Values.volume.name | default "pv" }}
  